# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa3df98701d3a5acb37ab9cf0dc208dc643e2ca31c4b3ac0f3c915bb58bdb942552efbc33d00a2d25b0d5632c5b45d2a280aeefa0f55d6c7a1792d31d333d5a

test:
  secret_key_base: 90659da97a0017e044546f9c67e52cc1a42721559341a2b2b5512936ee0861cecc71954a64dbc167ee17dad9603e20cac3dc4766586f2ede583fb38d6b9f99c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
